import type { StoryObj } from '@storybook/react';
declare const meta: {
    component: <T extends import("react").ElementType = "div">(props: import("./typography.tsx").TypographyProps<T>) => import("react/jsx-runtime").JSX.Element;
    tags: string[];
    title: string;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AllTypography: Story;
export declare const H1: Story;
export declare const H2: Story;
export declare const H3: Story;
export declare const H4: Story;
export declare const Body1: Story;
export declare const Body2: Story;
export declare const Subtitle1: Story;
export declare const Subtitle2: Story;
export declare const Caption: Story;
export declare const Overline: Story;
export declare const Link1: Story;
export declare const Link2: Story;
